destinations =  {
    "France": {"country": "France", "continent": "Europe", "activity": ["cultural", "urban"],
               "climate": "temperate", "budget": "high", "popularity": "popular", "vibe": "historic",
               "language": "english-friendly"},
    "Iceland": {"country": "Iceland", "continent": "Europe", "activity": ["adventure"], "climate": "cold",
                "budget": "high", "popularity": "under the radar", "vibe": "exotic",
                "language": "english-friendly"},
    "New York": {"country": "United States", "continent": "North America", "activity": ["cultural", "urban"],
                 "climate": "temperate", "budget": "high", "popularity": "popular", "vibe": "modern",
                 "language": "english-friendly"},
    "Tokyo": {"country": "Japan", "continent": "Asia", "activity": ["cultural", "urban"], "climate": "temperate",
              "budget": "high", "popularity": "popular", "vibe": "modern",
              "language": "language barrier doesn’t matter"},
    "Costa Rica": {"country": "Costa Rica", "continent": "North America", "activity": ["adventure", "relaxation"],
                   "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "exotic",
                   "language": "english-friendly"},
    "Switzerland": {"country": "Switzerland", "continent": "Europe", "activity": ["adventure", "relaxation"],
                    "climate": "cold", "budget": "high", "popularity": "popular", "vibe": "cozy",
                    "language": "english-friendly"},
    "Thailand": {"country": "Thailand", "continent": "Asia", "activity": ["cultural", "relaxation"],
                 "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "exotic",
                 "language": "language barrier doesn’t matter"},
    "Australia": {"country": "Australia", "continent": "Australia", "activity": ["adventure", "urban"],
                  "climate": "hot", "budget": "high", "popularity": "popular", "vibe": "modern",
                  "language": "english-friendly"},
    "Canada": {"country": "Canada", "continent": "North America", "activity": ["adventure", "relaxation"],
               "climate": "cold", "budget": "high", "popularity": "popular", "vibe": "cozy",
               "language": "english-friendly"},
    "Italy": {"country": "Italy", "continent": "Europe", "activity": ["cultural", "relaxation"],
              "climate": "temperate", "budget": "high", "popularity": "popular", "vibe": "historic",
              "language": "english-friendly"},
    "Brazil": {"country": "Brazil", "continent": "South America", "activity": ["adventure", "urban"],
               "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "exotic",
               "language": "language barrier doesn’t matter"},
    "Norway": {"country": "Norway", "continent": "Europe", "activity": ["adventure", "relaxation"],
               "climate": "cold", "budget": "high", "popularity": "under the radar", "vibe": "cozy",
               "language": "english-friendly"},
    "Vietnam": {"country": "Vietnam", "continent": "Asia", "activity": ["cultural", "adventure"],
                "climate": "tropical", "budget": "low", "popularity": "popular", "vibe": "exotic",
                "language": "language barrier doesn’t matter"},
    "South Africa": {"country": "South Africa", "continent": "Africa", "activity": ["adventure", "cultural"],
                     "climate": "hot", "budget": "medium", "popularity": "popular", "vibe": "exotic",
                     "language": "english-friendly"},
    "Greece": {"country": "Greece", "continent": "Europe", "activity": ["cultural", "relaxation"], "climate": "hot",
               "budget": "medium", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "New Zealand": {"country": "New Zealand", "continent": "Australia", "activity": ["adventure", "relaxation"],
                    "climate": "temperate", "budget": "high", "popularity": "under the radar", "vibe": "cozy",
                    "language": "english-friendly"},
    "Mexico": {"country": "Mexico", "continent": "North America", "activity": ["cultural", "urban"],
               "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "historic",
               "language": "english-friendly"},
"Japan": {"country": "Japan", "continent": "Asia", "activity": ["cultural", "urban"], "climate": "temperate",
              "budget": "high", "popularity": "popular", "vibe": "modern",
              "language": "language barrier doesn’t matter"},
    "Morocco": {"country": "Morocco", "continent": "Africa", "activity": ["cultural", "relaxation"],
                "climate": "hot", "budget": "medium", "popularity": "popular", "vibe": "historic",
                "language": "language barrier doesn’t matter"},
    "Dubai": {"country": "United Arab Emirates", "continent": "Asia", "activity": ["urban", "relaxation"],
              "climate": "hot", "budget": "high", "popularity": "popular", "vibe": "modern",
              "language": "english-friendly"},
    "Egypt": {"country": "Egypt", "continent": "Africa", "activity": ["cultural", "adventure"], "climate": "hot", "budget": "medium", "popularity": "popular", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Poland": {"country": "Poland", "continent": "Europe", "activity": ["cultural", "urban"], "climate": "temperate", "budget": "medium", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "Hungary": {"country": "Hungary", "continent": "Europe", "activity": ["cultural", "urban"], "climate": "temperate", "budget": "medium", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "Austria": {"country": "Austria", "continent": "Europe", "activity": ["cultural", "relaxation"], "climate": "temperate", "budget": "high", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "Czech Republic": {"country": "Czech Republic", "continent": "Europe", "activity": ["cultural", "urban"], "climate": "temperate", "budget": "medium", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "Croatia": {"country": "Croatia", "continent": "Europe", "activity": ["relaxation", "cultural"], "climate": "temperate", "budget": "medium", "popularity": "popular", "vibe": "cozy", "language": "english-friendly"},
    "Serbia": {"country": "Serbia", "continent": "Europe", "activity": ["cultural"], "climate": "temperate", "budget": "low", "popularity": "under the radar", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Romania": {"country": "Romania", "continent": "Europe", "activity": ["adventure", "cultural"], "climate": "temperate", "budget": "low", "popularity": "under the radar", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Bulgaria": {"country": "Bulgaria", "continent": "Europe", "activity": ["relaxation", "cultural"], "climate": "temperate", "budget": "low", "popularity": "under the radar", "vibe": "cozy", "language": "language barrier doesn’t matter"},
    "South Korea": {"country": "South Korea", "continent": "Asia", "activity": ["cultural", "urban"], "climate": "temperate", "budget": "high", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Taiwan": {"country": "Taiwan", "continent": "Asia", "activity": ["cultural", "urban"], "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Malaysia": {"country": "Malaysia", "continent": "Asia", "activity": ["cultural", "urban"], "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Philippines": {"country": "Philippines", "continent": "Asia", "activity": ["relaxation", "cultural"], "climate": "tropical", "budget": "low", "popularity": "popular", "vibe": "exotic", "language": "english-friendly"},

    "Singapore": {"country": "Singapore", "continent": "Asia", "activity": ["urban", "relaxation"], "climate": "tropical", "budget": "high", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Indonesia": {"country": "Indonesia", "continent": "Asia", "activity": ["adventure", "relaxation"], "climate": "tropical", "budget": "low", "popularity": "popular", "vibe": "exotic", "language": "language barrier doesn’t matter"},
    "Sri Lanka": {"country": "Sri Lanka", "continent": "Asia", "activity": ["adventure", "cultural"], "climate": "tropical", "budget": "low", "popularity": "under the radar", "vibe": "exotic", "language": "language barrier doesn’t matter"},
    "Uzbekistan": {"country": "Uzbekistan", "continent": "Asia", "activity": ["cultural"], "climate": "temperate", "budget": "low", "popularity": "under the radar", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Kazakhstan": {"country": "Kazakhstan", "continent": "Asia", "activity": ["adventure", "cultural"], "climate": "cold", "budget": "low", "popularity": "under the radar", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Madagascar": {"country": "Madagascar", "continent": "Africa", "activity": ["adventure", "relaxation"], "climate": "tropical", "budget": "low", "popularity": "under the radar", "vibe": "exotic", "language": "language barrier doesn’t matter"},
    "Tanzania": {"country": "Tanzania", "continent": "Africa", "activity": ["adventure", "cultural"], "climate": "tropical", "budget": "low", "popularity": "under the radar", "vibe": "exotic", "language": "language barrier doesn’t matter"},
    "Kenya": {"country": "Kenya", "continent": "Africa", "activity": ["adventure", "cultural"], "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "exotic", "language": "english-friendly"},
    "Colombia": {"country": "Colombia", "continent": "South America", "activity": ["adventure", "urban"], "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Bolivia": {"country": "Bolivia", "continent": "South America", "activity": ["adventure", "cultural"], "climate": "temperate", "budget": "low", "popularity": "under the radar", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Paraguay": {"country": "Paraguay", "continent": "South America", "activity": ["adventure", "relaxation"], "climate": "temperate", "budget": "low", "popularity": "under the radar", "vibe": "cozy", "language": "language barrier doesn’t matter"},
    "Uruguay": {"country": "Uruguay", "continent": "South America", "activity": ["relaxation", "cultural"], "climate": "temperate", "budget": "medium", "popularity": "under the radar", "vibe": "cozy", "language": "english-friendly"},
    "Guatemala": {"country": "Guatemala", "continent": "North America", "activity": ["cultural", "adventure"], "climate": "tropical", "budget": "low", "popularity": "under the radar", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Panama": {"country": "Panama", "continent": "North America", "activity": ["relaxation", "cultural"], "climate": "tropical", "budget": "medium", "popularity": "under the radar", "vibe": "modern", "language": "english-friendly"},
    "Cuba": {"country": "Cuba", "continent": "North America", "activity": ["cultural", "relaxation"], "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Jamaica": {"country": "Jamaica", "continent": "North America", "activity": ["relaxation", "cultural"], "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "exotic", "language": "english-friendly"},
    "Bahamas": {"country": "Bahamas", "continent": "North America", "activity": ["relaxation", "urban"], "climate": "tropical", "budget": "high", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Dominican Republic": {"country": "Dominican Republic", "continent": "North America", "activity": ["relaxation", "cultural"], "climate": "tropical", "budget": "medium", "popularity": "popular", "vibe": "exotic", "language": "language barrier doesn’t matter"},
    "Saudi Arabia": {"country": "Saudi Arabia", "continent": "Asia", "activity": ["cultural", "urban"], "climate": "hot", "budget": "high", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "Qatar": {"country": "Qatar", "continent": "Asia", "activity": ["urban", "relaxation"], "climate": "hot", "budget": "high", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Israel": {"country": "Israel", "continent": "Asia", "activity": ["cultural", "urban"], "climate": "hot", "budget": "high", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "Pakistan": {"country": "Pakistan", "continent": "Asia", "activity": ["adventure", "cultural"], "climate": "hot", "budget": "low", "popularity": "under the radar", "vibe": "historic", "language": "language barrier doesn’t matter"},
    "Nepal": {"country": "Nepal", "continent": "Asia", "activity": ["adventure"], "climate": "cold", "budget": "low",
              "popularity": "under the radar", "vibe": "exotic", "language": "english-friendly"},
    "Russia": {"country": "Russia", "continent": "Europe", "activity": ["cultural", "adventure"], "climate": "cold",
               "budget": "medium", "popularity": "under the radar", "vibe": "historic",
               "language": "language barrier doesn’t matter"},
    "Chile": {"country": "Chile", "continent": "South America", "activity": ["adventure", "relaxation"],
              "climate": "temperate", "budget": "medium", "popularity": "under the radar", "vibe": "cozy",
              "language": "language barrier doesn’t matter"},
    "Spain": {"country": "Spain", "continent": "Europe", "activity": ["cultural", "relaxation"], "climate": "temperate",
              "budget": "medium", "popularity": "popular", "vibe": "historic", "language": "english-friendly"},
    "Denmark": {"country": "Denmark", "continent": "Europe", "activity": ["cultural", "urban"], "climate": "cold",
                "budget": "high", "popularity": "popular", "vibe": "modern", "language": "english-friendly"},
    "Finland": {"country": "Finland", "continent": "Europe", "activity": ["adventure", "relaxation"], "climate": "cold",
                "budget": "high", "popularity": "under the radar", "vibe": "cozy", "language": "english-friendly"},
    "Ireland": {
        "country": "Ireland",
        "continent": "Europe",
        "activity": ["cultural", "urban"],
        "climate": "temperate",
        "budget": "high",
        "popularity": "popular",
        "vibe": "cozy",
        "language": "english-friendly"
    },
    "Belgium": {
        "country": "Belgium",
        "continent": "Europe",
        "activity": ["cultural", "urban"],
        "climate": "temperate",
        "budget": "high",
        "popularity": "popular",
        "vibe": "historic",
        "language": "english-friendly"
    },
    "Mongolia": {
        "country": "Mongolia",
        "continent": "Asia",
        "activity": ["adventure", "relaxation"],
        "climate": "Cold",
        "budget": "Low",
        "popularity": "Under the radar"
    },
    "Algeria": {
        "country": "Algeria",
        "continent": "Africa",
        "activity": ["cultural", "adventure"],
        "climate": "Hot",
        "budget": "Low",
        "popularity": "Under the radar"
    },
    "Ethiopia": {
        "country": "Ethiopia",
        "continent": "Africa",
        "activity": ["cultural", "adventure"],
        "climate": "Hot",
        "budget": "Low",
        "popularity": "Under the radar"
    }
}